; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5

# List of needed libraries and depedencies
lib_deps = 
    # ADXL345 sensor library
    adafruit/Adafruit ADXL345 @ ^1.3.0

    # Json library for Arduino
    bblanchon/ArduinoJson @ ^6.17.3

    # MQTT library
    mlesniew/PicoMQTT@^1.3.0

    # Enable logs on Arduino
    thijse/ArduinoLog @ ^1.0.3

# Extra script for environment variables loading
extra_scripts = loadenv.py

# Environment variables flags
build_flags = 
    -DWIFI_SSID=${sysenv.WIFI_SSID}
    -DWIFI_PASSWORD=${sysenv.WIFI_PASSWORD}
    -DMQTT_USERNAME=${sysenv.MQTT_USERNAME}
    -DMQTT_PASSWORD=${sysenv.MQTT_PASSWORD}
    -DMQTT_SERVER=${sysenv.MQTT_SERVER}
    -DMQTT_PORT=${sysenv.MQTT_PORT}
    -DDEVICE_NAME=${sysenv.DEVICE_NAME}